
version: 0.1

phases:   
  build:
    commands:
      - echo "Hello World"
      - export key='sikandar-keypair-ohio'
      
      
artifacts:
  files:
    - cf_parameters.json
  name: artifact-name
  discard-paths: yes      
