
version: 0.1

phases:   
  build:
    commands:
      - echo "Hello World"
      - yum install jq -y
      - echo '{"Parameters":{"key":"sikandar-keypair-ohio"}}' | jq . >output.json
#       - echo {'Parameters':{'key':'sikandar-keypair-ohio'}} | jq .  >output.json
#       - export jsonText={'Parameters':{"key" : "sikandar-keypair-ohio"}} | jq .  >output.json
#       - jo -p Parameters=$(jo key=sikandar-keypair-ohio)> output.json  
  #       - jo "{"Parameters" : {"key" : "sikandar-keypair-ohio"}}" > output.json  
#       - export key='sikandar-keypair-ohio'

artifacts:
  files:
    - output.json
  name: artifact-name
  discard-paths: yes      
