
version: 0.1

phases:   
  build:
    commands:
      - echo "Hello World"
      - key="sikandar-keypair-ohio"
      - echo $key
      - echo '{"Parameters":{"key":"'$key'"}}' | jq . >output.json
      - cat output.json 

artifacts:
  files:
    - output.json
  name: artifact-name
  discard-paths: yes      
