
version: 0.1

phases:  
  install:
    commands:
      - key=$(echo "sikandar-keypair-ohio")
  build:
    commands:
      - echo "Hello World"
      - echo $key
      - echo '{"Parameters":{"key":"'$key'"}}' | jq . >output.json
      - cat output.json 

artifacts:
  files:
    - output.json
  name: artifact-name
  discard-paths: yes      
