
version: 0.1

phases:   
  build:
    commands:
      - echo "Hello World"
      - export key='sikandar-keypair-ohio'
      - echo  '{"Parameters" : {"key" : "sikandar-keypair-ohio"}}' > output.json  
      
artifacts:
  files:
    - output.json
  name: artifact-name
  discard-paths: yes      
