
version: 0.1

phases:   
  build:
    commands:
      - echo "Hello World"
      - pecl install json
      - jo -p Parameters=$(jo key=sikandar-keypair-ohio)> output.json  
#       - jo "{"Parameters" : {"key" : "sikandar-keypair-ohio"}}" > output.json  
#       - export key='sikandar-keypair-ohio'

artifacts:
  files:
    - output.json
  name: artifact-name
  discard-paths: yes      
